name: Deploy Feature

on:
  workflow_dispatch:

jobs:
  deploy-feature-dev:
    name: Deploy Feature Branch
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PA }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_PA }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
