name: Deploy Feature

on:
  workflow_dispatch:
    inputs:
      run-terraform:
        type: boolean
        description: Run terraform?
        required: false
        default: false
      run-apigee:
        type: boolean
        description: Run Apigee job?
        required: false
        default: false

jobs:
#  deploy-feature-dev:
#    name: Deploy Feature Branch
#    uses: ./.github/workflows/deploy_resources.yml
#    secrets:
#      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
#      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
#      dft_organisation: ${{ secrets.DFT_ORGANISATION }}
#      dft_organisation_id: ${{ secrets.DFT_ORGANISATION_ID }}
#      access_level_members: ${{ secrets.ACCESS_LEVEL_MEMBERS }}
#    with:
#      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
#      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
#      environment: dev
##      do-validation-checks: true
#      checkov-skip-check: ${{ vars.CHECKOV_SKIP_CHECK }}
#      run-terraform: ${{ inputs.run-terraform }}
#      run-apigee: ${{ inputs.run-apigee }}

  deploy-feature-test:
    name: Deploy Feature Branch
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_TEST }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT_TEST }}
      dft_organisation: ${{ secrets.DFT_ORGANISATION }}
      dft_organisation_id: ${{ secrets.DFT_ORGANISATION_ID }}
      access_level_members: ${{ secrets.ACCESS_LEVEL_MEMBERS }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_TEST }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: test
      #      do-validation-checks: true
      checkov-skip-check: ${{ vars.CHECKOV_SKIP_CHECK }}
      run-terraform: ${{ inputs.run-terraform }}
      run-apigee: ${{ inputs.run-apigee }}