name: Deploy Feature

on:
  workflow_dispatch:
    inputs:
      run-terraform:
        type: boolean
        description: Run terraform?
        required: false
        default: false
      run-apigee-1:
        type: boolean
        description: Run Apigee job 1?
        required: false
        default: false

jobs:
  deploy-feature-dev:
    name: Deploy Feature Branch
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
      dft_organisation: ${{ secrets.DFT_ORGANISATION }}
      dft_organisation_id: ${{ secrets.DFT_ORGANISATION_ID }}
      access_level_members: ${{ secrets.ACCESS_LEVEL_MEMBERS }}
      apigee_service_endpoint: ${{ secrets.APIGEE_SERVICE_ENDPOINT_DEV }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
#      do-validation-checks: true
      checkov-skip-check: ${{ vars.CHECKOV_SKIP_CHECK }}
      run-terraform: ${{ inputs.run-terraform }}
      run-apigee-1: ${{ inputs.run-apigee-1 }}
