name: Deploy Feature

on:
  workflow_dispatch:

jobs:
#  docker-build-push:
#    name: Build and push Docker image to Artifact Registry
#    uses: ./.github/workflows/docker-build-push.yml

#  deploy-feature-dev-pa:
#    name: Deploy Feature Branch
#    uses: ./.github/workflows/deploy_resources.yml
#    secrets:
#      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PA }}
#      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_PA }}
#      cloud_run_service_account: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_PA }}
#    with:
#      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV_PA }}
#      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
#      environment: dev
  deploy-feature-dev:
    name: Deploy Feature Branch
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      cloud_run_service_account: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
