name: Build and push Docker image to Artifact Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout this infra respository
        uses: actions/checkout@v4

      - name: Checkout the dtro-beta repository
        uses: actions/checkout@v4
        with:
          repository: pa-digital/dft-dtro-beta
          token: ${{ secrets.GITHUB_TOKEN }}
          path: dft-dtro-beta

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PA }}
          service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_PA }}

      - name: Authenticate Docker with the Artifact Registry repository
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v3
        with:
          context: ./dft-dtro-beta
          push: true
          tags: europe-west1-docker.pkg.dev/pa-tc-sandbox-341312/pa-tc-sandbox-341312/dft-dtro-beta:${{ github.sha }}

