name: Merge To Main

on:
  workflow_dispatch:
# TODO: Once GCP infrastructure are in place, this workflow will be triggered by merging of a PR to Main
#  push:
#    branches:
#      - main

jobs:
  deploy-dev:
    name: Terraform - Deploy to Dev
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
      dft_organisation: ${{ secrets.DFT_ORGANISATION }}
      dft_organisation_id: ${{ secrets.DFT_ORGANISATION_ID }}
      access_level_members: ${{ secrets.ACCESS_LEVEL_MEMBERS }}
      iap_client_id: ${{ secrets.IAP_CLIENT_ID_DEV }}
      iap_client_secret: ${{ secrets.IAP_CLIENT_SECRET_DEV }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
      run-terraform: true
      run-apigee: false #TODO: Default value when no major endpoint or OAuth changes have been made
#      run-apigee: true

  deploy-test:
    name: Terraform - Deploy to Test
    uses: ./.github/workflows/deploy_resources.yml
    needs:
      - terraform-deploy-dev
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_TEST }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT_TEST }}
      dft_organisation: ${{ secrets.DFT_ORGANISATION }}
      dft_organisation_id: ${{ secrets.DFT_ORGANISATION_ID }}
      access_level_members: ${{ secrets.ACCESS_LEVEL_MEMBERS }}
      iap_client_id: ${{ secrets.IAP_CLIENT_ID_TEST }}
      iap_client_secret: ${{ secrets.IAP_CLIENT_SECRET_TEST }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_TEST }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: test
      run-terraform: true
      run-apigee: false #TODO: Default value when no major endpoint or OAuth changes have been made
#      run-apigee: true
