name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.wip_service_account }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: terraform validate
        uses: dflook/terraform-validate@v1

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config "bucket=${{env.TF_VAR_tf_state_bucket}}" \
          -backend-config "prefix=terraform/state"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: terraform validate
        uses: dflook/terraform-validate@v1

      - name: Terraform Plan
        run: terraform plan -input=false -out=plan.out && terraform show -json plan.out > plan.out.json

      - name: terraform-compliance
        uses: terraform-compliance/github_action@main
        with:
          plan: plan.out.json
          features: ssh://git@github.com/terraform-compliance/user-friendly-features.git
