name: Validate Feature

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
      - bug/*
      - hotfix/*

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  build-feature:
    name: Test and Validate Feature Branch
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v2
#        with:
#          create_credentials_file: true
#          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#          service_account: ${{ secrets.WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: terraform validate
        uses: dflook/terraform-validate@v1

      - name: Terraform Init
        run: terraform init

#      - name: terraform validate
#        uses: dflook/terraform-validate@v1
#
#      - name: Terraform Plan
#        run: terraform plan -input=false -out=plan.out && terraform show -json plan.out > plan.out.json
#
#      - name: terraform-compliance
#        uses: terraform-compliance/github_action@main
#        with:
#          plan: plan.out.json
#          features: ssh://git@github.com/terraform-compliance/user-friendly-features.git
